/**
 * generate-theme.ts — CRM theme generator
 *
 * Reads GAIA design tokens and writes apps/crm/app/globals.css with
 * shadcn/ui CSS variable blocks for both light and dark modes.
 *
 * Usage (run from apps/crm/):
 *   pnpm generate-theme
 *   # or directly:
 *   pnpm tsx scripts/generate-theme.ts
 *
 * Run whenever packages/shared/tokens/colors.ts or tokens/radii.ts changes.
 * The emitted globals.css is committed and tracked in git.
 *
 * Token → variable chain:
 *
 *   packages/shared/tokens/colors.ts   ← single source of truth (hex values)
 *           │
 *           ▼
 *   scripts/generate-theme.ts          ← converts hex→HSL, defines light+dark mapping
 *           │
 *           ▼
 *   app/globals.css  :root { --primary: … }   ← CSS custom properties (HSL components)
 *           │
 *           ▼
 *   tailwind.config.ts  primary: 'hsl(var(--primary))'   ← Tailwind semantic colors
 *           │
 *           ▼
 *   components/ui/*.tsx  className="bg-primary text-primary-foreground"
 *
 * Dark mode:
 *   Add class="dark" to <html> to activate the .dark block.
 *   The CRM ships light-first; dark vars are present and tested.
 *   In dark mode --primary flips to brand.accent (gold) because brand.primary
 *   (forest green) cannot contrast against a forest-green background.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';

// Import token source directly (relative path bypasses the dist/ requirement,
// so this script runs without building @gaia/shared first).
import { brand, surface, text, state } from '../../../packages/shared/tokens/colors';
import { radii } from '../../../packages/shared/tokens/radii';

/** Convert a 6-digit CSS hex color to "H S% L%" string (no hsl() wrapper). */
function hexToHsl(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

const hsl = hexToHsl;

// Dark-mode border/input: brand.primary HSL (154 40% 17%) with lightness bumped
// to ~27% for contrast against the card background. Not in the token set because
// it only exists as a dark-mode UI detail, not a semantic design decision.
const DARK_BORDER = '154 30% 27%';
const DARK_INPUT  = '154 35% 22%';

const globals = `/* Auto-generated by apps/crm/scripts/generate-theme.ts — do not edit by hand.
 * Run: pnpm --filter @gaia/crm generate-theme
 * Source: packages/shared/tokens/colors.ts + tokens/radii.ts
 */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  /* ─── Light mode ─────────────────────────────────────────────────────────── */
  :root {
    /* Backgrounds */
    --background:             ${hsl(surface.bg)};     /* surface.bg      ${surface.bg} */
    --foreground:             ${hsl(text.primary)};   /* text.primary    ${text.primary} */

    --card:                   ${hsl(surface.card)};   /* surface.card    ${surface.card} */
    --card-foreground:        ${hsl(text.primary)};

    --popover:                ${hsl(surface.white)};  /* surface.white   ${surface.white} */
    --popover-foreground:     ${hsl(text.primary)};

    /* Brand — forest green */
    --primary:                ${hsl(brand.primary)};  /* brand.primary   ${brand.primary} */
    --primary-foreground:     ${hsl(surface.bg)};     /* cream on green */

    --secondary:              ${hsl(surface.card)};
    --secondary-foreground:   ${hsl(text.primary)};

    --muted:                  ${hsl(surface.card)};
    --muted-foreground:       ${hsl(text.secondary)}; /* text.secondary  ${text.secondary} */

    /* Brand — gold accent */
    --accent:                 ${hsl(brand.accent)};   /* brand.accent    ${brand.accent} */
    --accent-foreground:      ${hsl(surface.white)};  /* white on gold */

    /* Destructive — counterfeit / error red */
    --destructive:            ${hsl(state.error)};    /* state.error     ${state.error} */
    --destructive-foreground: ${hsl(surface.white)};

    --border:                 ${hsl(surface.border)}; /* surface.border  ${surface.border} */
    --input:                  ${hsl(surface.border)};
    --ring:                   ${hsl(brand.primary)};  /* focus ring = brand green */

    --radius: ${radii.md / 16}rem; /* radii.md = ${radii.md}px */
  }

  /* ─── Dark mode ──────────────────────────────────────────────────────────── */
  /* Activate with <html class="dark">. CRM ships light-first; dark is ready.  */
  .dark {
    /* Backgrounds — deep forest green shell */
    --background:             ${hsl(brand.dark)};         /* brand.dark          ${brand.dark} */
    --foreground:             ${hsl(text.onDark)};        /* text.onDark         ${text.onDark} */

    --card:                   ${hsl(brand.primary)};      /* brand.primary       ${brand.primary} */
    --card-foreground:        ${hsl(text.onDark)};

    --popover:                ${hsl(brand.dark)};
    --popover-foreground:     ${hsl(text.onDark)};

    /* Primary flips to gold — green-on-green has no contrast */
    --primary:                ${hsl(brand.accent)};       /* brand.accent        ${brand.accent} */
    --primary-foreground:     ${hsl(brand.dark)};

    --secondary:              ${hsl(brand.primaryHover)}; /* brand.primaryHover  ${brand.primaryHover} */
    --secondary-foreground:   ${hsl(text.onDark)};

    --muted:                  ${hsl(brand.primaryHover)};
    --muted-foreground:       ${hsl(text.disabled)};      /* text.disabled       ${text.disabled} */

    --accent:                 ${hsl(brand.accent)};
    --accent-foreground:      ${hsl(brand.dark)};

    --destructive:            ${hsl(state.error)};
    --destructive-foreground: 0 0% 100%;

    /* Border/input: brand.primary + lightness bump (see script comment) */
    --border: ${DARK_BORDER};
    --input:  ${DARK_INPUT};
    --ring:   ${hsl(brand.accent)};  /* gold focus ring on dark green */
  }

  /* ─── Base styles ────────────────────────────────────────────────────────── */
  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground;
    font-family: var(--font-inter), ui-sans-serif, system-ui, sans-serif;
  }

  h1,
  h2 {
    font-family: var(--font-playfair), ui-serif, Georgia, serif;
  }

  /* Focus visibility contract ────────────────────────────────────────────────
   * All interactive shadcn/ui components emit:
   *   focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2
   * which resolves to a 2px solid ring at hsl(var(--ring)).
   * Light mode ring: brand.primary (forest green) on cream — passes WCAG AA.
   * Dark mode ring:  brand.accent  (gold)         on dark green — passes WCAG AA.
   * The :focus-visible rule below is a backstop for any non-shadcn elements.
   */
  :focus-visible {
    outline: 2px solid hsl(var(--ring));
    outline-offset: 2px;
  }
}
`;

const outPath = resolve(process.cwd(), 'app/globals.css');
writeFileSync(outPath, globals, 'utf8');
console.log(`✓  Written ${outPath}`);
